#!/bin/bash
#
# Recursively fix file permissions
# Must run as root
#
# This source file is part of the follwoing repository:
# http://www.github.com/microfarad-de/nastia-server
#
# Please visit:
#   http://www.microfarad.de
#   http://www.github.com/microfarad-de
#
# Copyright (C) 2019 Karim Hraibi (khraibi@gmail.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# Path to the current directory where this script is located
DIR=$(dirname $(readlink -f "$BASH_SOURCE"))

# Include common configuration file
source "$DIR/common.sh"

# Log file
LOG="$CFG_LOG_DIR/permissions.log"

EXIT_CODE=0

# Print an info log message
function infoLog {
  _infoLog "$1" "permissions" "$LOG" "ecd"
}

# Print a warning log message
function warningLog {
  _warningLog "$1" "permissions" "$LOG" "ecd"
}

# Print an error log message
function errorLog {
  _errorLog "$1" "permissions" "$LOG" "ecd"
  EXIT_CODE=1
}


function main {
  local dir="$1"
  local user="$2"
  local group="$3"
  local dmode="$4"
  local fmode="$5"

  echo chown -R "$user":"$group" "$dir"
  chown -R "$user":"$group" "$dir"
  rv=$?;
  if [[ $rv -ne 0 ]]; then
    errorLog "chown $user:$group $dir failed (exit code $rv)"
  fi
  echo find "$dir" -type d -exec chmod "$dmode" {} +
  find "$dir" -type d -exec chmod "$dmode" {} +
  rv=$?
  if [[ $rv -ne 0 ]]; then
    errorLog "chmod $dmode $dir (d) failed (exit code $rv)"
  fi
  echo find "$dir" -type f -exec chmod "$fmode" {} +
  find "$dir" -type f -exec chmod "$fmode" {} +
  rv=$?
  if [[ $rv -ne 0 ]]; then
    errorLog "chmod $fmode $dir (f) failed (exit code $rv)"
  fi
}


#################
####  START  ####
#################



# Loop over config items
for i in "${!CFG_PERMISSION_SET[@]}"; do
  main ${CFG_PERMISSION_SET[$i]}
done

if [[ $EXIT_CODE -eq 0 ]]; then
  infoLog "permissions applied successfully"
fi

exit $EXIT_CODE
