#!/bin/bash
#
# Backup SD card image to a remote SSH host
# Must run as root
#
# This source file is part of the follwoing repository:
# http://www.github.com/microfarad-de/nastia-server
#
# Please visit:
#   http://www.microfarad.de
#   http://www.github.com/microfarad-de
#
# Copyright (C) 2025 Karim Hraibi (khraibi@gmail.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

set -euo pipefail

# Path to the current directory where this script is located
SCRIPT_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"

# Include common configuration file
# shellcheck source=/dev/null
source "$SCRIPT_DIR/common.sh"

# Configuration parameters
DEVICE="$CFG_BACKUP_SD_DEVICE"
SSH_HOST="$CFG_BACKUP_SD_DEST_SSH"
DEST_DIR="$CFG_BACKUP_SD_DEST_DIR"
LOCK="$CFG_TMPFS_DIR/backup-sd.lock"
LOG="$CFG_LOG_DIR/backup-sd.log"

function infoLog {
  _infoLog "$1" "backup-sd" "$LOG" "ecd"
}

function warningLog {
  _warningLog "$1" "backup-sd" "$LOG" "ecd"
}

function errorLog {
  _errorLog "$1" "backup-sd" "$LOG" "ecd"
}

################
#### START  ####
################

# Always release lock on exit (success or failure)
cleanup() {
  semaphoreRelease "$LOCK" >/dev/null 2>&1 || true
}
trap cleanup EXIT

# Convert any command error into a logged error
trap 'rc=$?; errorLog "backup failed ($rc)"' ERR

# avoid multiple instances of this script
semaphoreLock "$LOCK" " "
if [[ $? -ne 0 ]]; then
  warningLog "an instance of the current script is already running (please remove $LOCK)"
  exit 1
fi

HOST="$(hostname -s)"
TS="$(date -u +%Y%m%d-%H%M%S)"
FILE="$HOST-$TS-sd.img"
REMOTE_OUT="$DEST_DIR/$FILE.zst"
REMOTE_TMP="$REMOTE_OUT.partial"

# Flush pending writes if available (don’t fail if blockdev isn’t present)
if command -v blockdev >/dev/null 2>&1; then
  blockdev --flushbufs "$DEVICE" || true
fi

# Stream: SD -> zstd (local compression) -> ssh (remote store), atomic on remote
dd if="$DEVICE" bs=4M \
| zstd -T0 -3 -v \
| ssh "$SSH_HOST" "cat > '$REMOTE_TMP' && mv -f '$REMOTE_TMP' '$REMOTE_OUT'"

infoLog "backup completed: $SSH_HOST:$REMOTE_OUT"

exit 0



