#!/bin/bash
#
# Daemon script, enables GPIO acces to non root users
#
# The gpio command is written into the file /tmp/gpio
# with the following format: <pin> <value>
#
# Example: echo "26 1" > /tmp/gpio
#
# This source file is part of the follwoing repository:
# http://www.github.com/microfarad-de/nastia-server
#
# Please visit:
#   http://www.microfarad.de
#   http://www.github.com/microfarad-de
#
# Copyright (C) 2023 Karim Hraibi (khraibi@gmail.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

GPIO_FILE="/tmp/gpio"

log() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1"
}

init_gpio() {
    PIN=$1
    if [ ! -d "/sys/class/gpio/gpio${PIN}" ]; then
        echo "$PIN" > /sys/class/gpio/export
        sleep 0.1
    fi

    # Set direction to out if not already
    CURRENT_DIR=$(cat /sys/class/gpio/gpio${PIN}/direction)
    if [ "$CURRENT_DIR" != "out" ]; then
        echo "out" > "/sys/class/gpio/gpio${PIN}/direction"
    fi
}

set_gpio_value() {
    PIN=$1
    VALUE=$2
    echo "$VALUE" > "/sys/class/gpio/gpio${PIN}/value"
    log "Set GPIO $PIN to $VALUE"
}

log "GPIO daemon started."

while true; do
    if [ -f "$GPIO_FILE" ]; then
        while read -r PIN VALUE; do
            # Validate inputs
            if echo "$PIN" | grep -Eq '^[0-9]+$' && { [ "$VALUE" = "0" ] || [ "$VALUE" = "1" ]; }; then
                init_gpio "$PIN"
                set_gpio_value "$PIN" "$VALUE"
            else
                log "Invalid format: '$PIN $VALUE'"
            fi
        done < "$GPIO_FILE"

        rm -f "$GPIO_FILE"
    fi
    sleep 1
done

