#!/bin/bash
#
# Initialization Script
# This script is called by systemd after booting the system.
# Must run as root
#
# This source file is part of the follwoing repository:
# http://www.github.com/microfarad-de/nastia-server
#
# Please visit:
#   http://www.microfarad.de
#   http://www.github.com/microfarad-de
#
# Copyright (C) 2019 Karim Hraibi (khraibi@gmail.com)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# Current directory where this script is located
DIR=$(dirname $(readlink -f "$BASH_SOURCE"))

# Include common configuration file
source "$DIR/common.sh"



# Configuration parameters
LOG="$CFG_LOG_DIR/init.log"  # Main log file
PREFIX="init"                # Log prefix


# Print info message to log file
function infoLog {
  _infoLog "$1" "$PREFIX" "$LOG" "ecd"
}

# Print warning message to log file
function warningLog {
  _warningLog "$1" "$PREFIX" "$LOG" "ecd"
}

# Print error message to log file
function errorLog {
  _errorLog "$1" "$PREFIX" "$LOG" "ecd"
}




#################
####  START  ####
#################

infoLog "system startup..."

# Disable WLAN
if [[ $CFG_WLAN_DISABLE -eq 1 ]]; then
  /bin/sleep 10
  /sbin/ifconfig "$CFG_WLAN_INTERFACE" down
  rv=$?
  if [[ $rv -eq 0 ]]; then
    infoLog "$CFG_WLAN_INTERFACE disabled"
  else
    errorLog "failed to disable $CFG_WLAN_INTERFACE (exit code $rv)"
  fi
fi


exit 0


