#!/bin/sh
# KHr
### BEGIN INIT INFO
# Provides:          bt-daemon
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start bt-daemon on boot
# Description:       Starts the Python script to run MQTT integration
### END INIT INFO
SCRIPT_PATH="/opt/nastia-server/sbin/bt-daemon"
PIDFILE="/var/run/bt-daemon.pid"
LOGFILE="/var/log/bt-daemon.log"
USER="root"  # Or another user if appropriate

start() {
    echo "Starting bt-daemon..."
    if [ -f $PIDFILE ]; then
        echo "Already running (PID $(cat $PIDFILE))"
        return 1
    fi
    nohup $SCRIPT_PATH >> /dev/null 2>&1 &
    echo $! > $PIDFILE
    echo "Started with PID $(cat $PIDFILE)"
}

stop() {
    echo "Stopping bt-daemon..."
    if [ -f $PIDFILE ]; then
        kill $(cat $PIDFILE)
        rm -f $PIDFILE
        echo "Stopped."
    else
        echo "Not running."
    fi
}

status() {
    if [ -f $PIDFILE ]; then
        echo "bt-daemon is running (PID $(cat $PIDFILE))"
    else
        echo "bt-daemon is not running."
    fi
}

case "$1" in
    start) start ;;
    stop) stop ;;
    restart) stop && start ;;
    status) status ;;
    *) echo "Usage: $0 {start|stop|restart|status}" ;;
esac

exit 0
