#!/bin/sh
# KHr
### BEGIN INIT INFO
# Provides:          init
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start init on boot
# Description:       Starts the shell script for system initialization
### END INIT INFO
SCRIPT_PATH="/opt/nastia-server/sbin/init"
PIDFILE="/var/run/init.pid"
LOGFILE="/var/log/init.log"
DESC="init"

start() {
    echo "Starting $DESC..."
    if [ -f $PIDFILE ]; then
        echo "Already running (PID $(cat $PIDFILE))"
    else
        nohup $SCRIPT_PATH >> /dev/null 2>&1 &
        echo $! > $PIDFILE
        echo "Started with PID $(cat $PIDFILE)"
    fi
}

stop() {
    echo "Stopping $DESC..."
    if [ -f $PIDFILE ]; then
        PID=$(cat $PIDFILE)
        pkill -P "$PID"  # Kill child processes
        kill "$PID"      # Kill main process
        rm -f $PIDFILE
        echo "Stopped."
    else
        echo "Not running."
    fi
}

status() {
    if [ -f $PIDFILE ]; then
        PID=$(cat $PIDFILE)
        if kill -0 "$PID" 2>/dev/null; then
            echo "$DESC is running (PID $PID)"
            exit 0
        else
            echo "$DESC is not running, but PID file exists. Cleaning up."
            rm -f $PIDFILE
            exit 2
        fi
    else
        echo "$DESC is not running."
        exit 3
    fi
}


case "$1" in
    start) start ;;
    stop) stop ;;
    restart) stop && start ;;
    status) status ;;
    *)
    echo "Usage: $0 {start|stop|restart|status}" >&2
    exit 1;;
esac

exit 0
